#!/bin/bash
set -euo pipefail

BIN_TARGET=$(python -c "import os.path, sys; print(os.path.dirname(sys.executable))")
if [ -z "$BIN_TARGET" ] ; then
  echo "Could not find binaries target"
  exit 1
fi

if [ ! -w "$BIN_TARGET" ] ; then
  echo "Binaries target $BIN_TARGET is not writable!"
  exit 2
fi

GOBIN=$BIN_TARGET GO111MODULE=on go get github.com/norwoodj/helm-docs/cmd/helm-docs
