dependencies:
  - name: postgresql
    version: 8.9.4
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
  - name: redis
    version: 10.6.12
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
