{{- if .Values.extraSecretConfig -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
  {{- with .Values.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- range $key, $value := .Values.extraSecretConfig }}
  {{ $key }}: {{ tpl $value $ | b64enc | quote }}
  {{- end }}
{{- end -}}