{{- if not .Values.postgresql.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.weblate.externalPostgres.password | b64enc | quote }}
{{- end}}
---
{{- if not .Values.redis.enabled}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.weblate.externalRedis.password | b64enc | quote }}
{{- end}}