{{ if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "weblate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.auth.enablePostgresUser }}
  postgresql-user: {{ "postgres" | b64enc | quote }}
  {{- else }}
  postgresql-user: {{ .Values.postgresql.auth.postgresqlUsername | b64enc | quote }}
  {{- end }}
  postgresql-password: {{ .Values.postgresql.auth.postgresqlPassword | b64enc | quote }}
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
  email-user: {{ .Values.emailUser | b64enc | quote }}
  email-password: {{ .Values.emailPassword | b64enc | quote }}
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  admin-password: {{ .Values.adminPassword | b64enc | quote }}
{{ end }}
