{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "weblate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "weblate.labels" . | indent 4 }}
{{- end -}}
