# This file is maintained in https://github.com/WeblateOrg/meta/
name: Sync labels in the declarative way
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/label-sync.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        with:
          manifest: .github/labels.yml
